### ISSUE TITLE
Address TODO's in ParseXML.py

### ISSUE THREAD

**Issue by skeating** [sbmlteam/deviser#50]
- [x] to_int
- [x] get_enum_value
- [x] get_enum_name
- [x] find_lo_element
